#define _BVL(bit) (1UL << (bit))
#define set(reg,value) reg |= (value)
#define unset(reg,value) reg &= ~(value)
#define set_bit(reg,value) reg |= (_BVL(value))
#define set_bit2(reg,value1,value2) reg |= (_BVL(value1) | _BVL(value2))
#define set_bit3(reg,value1,value2,value3) reg |= (_BVL(value1) | _BVL(value2) | _BVL(value3))
#define set_bit4(reg,value1,value2,value3,value4) reg |= (_BVL(value1) | _BVL(value2) | _BVL(value3) | _BVL(value4))
#define set_bit5(reg,value1,value2,value3,value4,value5) reg |= (_BVL(value1) | _BVL(value2) | _BVL(value3) | _BVL(value4) | _BVL(value5))
#define unset_bit(reg,value) reg &= ~(_BVL(value))
#define unset_bit2(reg,value1,value2) reg &= ~(_BVL(value1) | _BVL(value2))
#define unset_bit3(reg,value1,value2,value3) reg &= ~(_BVL(value1) | _BVL(value2) | _BVL(value3))
#define unset_bit4(reg,value1,value2,value3,value4) reg &= ~(_BVL(value1) | _BVL(value2) | _BVL(value3) | _BVL(value4))
#define unset_bit5(reg,value1,value2,value3,value4,value5) reg &= ~(_BVL(value1) | _BVL(value2) | _BVL(value3) | _BVL(value4) | _BVL(value5))
