#define SMD_ENABLED
#define SMD_SECOND_ENABLED
#define SMD_SELECT_PORT D
#define SMD_SELECT_PIN 6
#define SMD_DATA_PORT D
#define SMD_DATA0_PIN 0
#define SMD_DATA1_PIN 1
#define SMD_DATA2_PIN 2
#define SMD_DATA3_PIN 3
#define SMD_DATA4_PIN 4
#define SMD_DATA5_PIN 5
#define SMD_DATA_PORT2 B
#define SMD_DATA0_PIN2 0
#define SMD_DATA1_PIN2 1
#define SMD_DATA2_PIN2 2
#define SMD_DATA3_PIN2 3
#define SMD_DATA4_PIN2 4
#define SMD_DATA5_PIN2 5
#define SMD_USE_DENDY9_PIN

#define NES_ENABLED
#define NES_SECOND_ENABLED
#define NES_PORT C
#define NES_LATCH_PIN 4
#define NES_CLOCK_PIN 5
#define NES_DATA_PIN 6
#define NES_DATA_PIN2 7

#define LED_PORT B
#define LED_RED_PIN 6
#define LED_GREEN_PIN 7

//#define LINUX_WORKAROUND
